/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kreemer' at '5/26/16 10:33 AM' with Gradle 2.9
 *
 * @author kreemer, @date 5/26/16 10:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
